export const algorithmCode = {
  bubble: [
    'for (let i = 0; i < n - 1; i++) {',
    '  for (let j = 0; j < n - i - 1; j++) {',
    '    if (arr[j] > arr[j + 1]) {',
    '      [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];',
    '    }',
    '  }',
    '}',
  ],
  selection: [
    'for (let i = 0; i < n - 1; i++) {',
    '  let minIdx = i;',
    '  for (let j = i + 1; j < n; j++) {',
    '    if (arr[j] < arr[minIdx]) {',
    '      minIdx = j;',
    '    }',
    '  }',
    '  [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
    '}',
  ],
  insertion: [
    'for (let i = 1; i < n; i++) {',
    '  let key = arr[i];',
    '  let j = i - 1;',
    '  while (j >= 0 && arr[j] > key) {',
    '    arr[j + 1] = arr[j];',
    '    j--;',
    '  }',
    '  arr[j + 1] = key;',
    '}',
  ],
} as const;